@url_dev=http://localhost:3005/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 965ab7d2099630bcdfd5e60143029624cde5050330bdf689

{
    "name": "test",
    "password": "test123",
    "email": "t1412es1212145@test.com"
}