version: '3'
services:
  my-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: node pool2.js
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: testpass
      MYSQL_PASSWORD: testpass
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    expose:
      - 3306
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g